/** Jeu d'exemple du mode démonstration. Jamais écrit sur l'appareil :
 *  il ne sert qu'à montrer l'application remplie. */

import type { Race } from './types.ts'

export const SAMPLE_RACES: Race[] = [
  {
    id: 'sample-1',
    type: 'ultra',
    name: 'UTMB',
    date: '2026-08-28',
    distance: 170,
    duration: '46:30:00',
    elevationGain: 10000,
    location: 'Chamonix',
    notes:
      'Finisher ! Nuit difficile après Courmayeur, remontée sur les 40 derniers kilomètres.',
  },
  {
    id: 'sample-2',
    type: '10k',
    name: '10k de Lyon',
    date: '2026-08-02',
    distance: 10,
    duration: '45:00',
    elevationGain: null,
    location: 'Lyon',
    notes: 'Parcours plat. Nouveau record !',
  },
  {
    id: 'sample-3',
    type: 'semi',
    name: 'Semi de Genève',
    date: '2026-07-05',
    distance: 21.1,
    duration: '1:38:20',
    elevationGain: 120,
    location: 'Genève',
    notes: '',
  },
  {
    id: 'sample-4',
    type: 'trail',
    name: 'Trail des Aiguilles',
    date: '2026-06-14',
    distance: 32,
    duration: '4:12:00',
    elevationGain: 1450,
    location: 'Chamonix',
    notes: 'Descente prudente, genou fragile.',
  },
  {
    id: 'sample-5',
    type: '5k',
    name: '5k du parc',
    date: '2026-06-07',
    distance: 5,
    duration: '21:40',
    elevationGain: null,
    location: 'Lyon',
    notes: '',
  },
  {
    id: 'sample-6',
    type: 'marathon',
    name: 'Marathon de Milan',
    date: '2026-04-19',
    distance: 42.2,
    duration: '3:32:10',
    elevationGain: 90,
    location: 'Milan',
    notes: 'Négative split tenu.',
  },
  {
    id: 'sample-7',
    type: '10k',
    name: '10k hivernal',
    date: '2026-02-15',
    distance: 10,
    duration: '43:12',
    elevationGain: null,
    location: 'Annecy',
    notes: '',
  },
  {
    id: 'sample-8',
    type: 'marathon',
    name: 'Marathon de Lausanne',
    date: '2025-10-12',
    distance: 42.2,
    duration: '3:41:05',
    elevationGain: 210,
    location: 'Lausanne',
    notes: '',
  },
  {
    id: 'sample-9',
    type: 'trail',
    name: 'Trail du Salève',
    date: '2025-05-24',
    distance: 24,
    duration: '2:58:00',
    elevationGain: 1100,
    location: 'Genève',
    notes: '',
  },
  {
    id: 'sample-10',
    type: 'marathon',
    name: 'Marathon de Paris',
    date: '2022-04-10',
    distance: 42.2,
    duration: '3:45:00',
    elevationGain: 200,
    location: 'Paris',
    notes: 'Objectif 3h30 raté à cause du vent.',
  },
]
